VERSION 0.8

optional-arg:
  ARG A

required-arg:
  ARG --required B

optional-default-arg:
  ARG C=D

optional-default-arg-2:
  ARG C=D=E

# This target has a documented ARG.
documented-arg:
  # The name to greet.
  ARG NAME

# Multiple ARGs in a single target.
multi-arg:
  ARG --required FOO
  ARG BAR=default-bar
  ARG BAZ

# Mix of builtin and user ARGs to verify filtering.
builtin-arg:
  ARG TARGETPLATFORM
  ARG EARTHLY_CI
  ARG REAL_ARG
